version: "3.7"
services:
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /Users/soo/Downloads/data/MariaDB:/var/lib/mysql
      - /Users/soo/Downloads/data/MariaDB/config:/etc/mysql/conf.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
